apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: dev
  labels:
    app: backend
spec:
  type: ClusterIP
  # Використовуйте ClusterIP для сервісів, які повинні бути доступні лише всередині кластера.
  # Використовуйте NodePort для швидкого доступу до сервісів ззовні кластера, якщо у вас немає зовнішнього балансувальника або ви тестуєте додаток
  selector:
    app: backend  # Переконайтеся, що мітка відповідає вашому поду
  ports:
    - port: 5000         # Порт, за яким сервіс буде доступний
      targetPort: 5000   # Порт, на якому слухає контейнер
      #nodePort: 30001    # Порт, за яким сервіс буде доступний ззовні (тільки для NodePort)