apiVersion: v1
kind: Service
metadata:
  name: api-app-service
spec:
  type: NodePort
  selector:
    app: api-app  # Переконайтеся, що мітка відповідає вашому поду
  ports:
    - port: 5000         # Порт, за яким сервіс буде доступний
      targetPort: 5000   # Порт, на якому слухає контейнер
      nodePort: 30001    # Порт, за яким сервіс буде доступний ззовні (опціонально)
