apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deploymentName }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.labels.app }}
spec:
  type: NodePort
  selector:
    app: backend  # Переконайтеся, що мітка відповідає вашому поду
  ports:
    - port: 5000         # Порт, за яким сервіс буде доступний
      targetPort: 5000   # Порт, на якому слухає контейнер
      nodePort: {{ .Values.service.nodePort }}    # Порт, за яким сервіс буде доступний ззовні
